# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.TextField()),
                ('repeat_password', models.TextField()),
                ('login_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
