# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_auto_20161125_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='signin',
            name='repeat_password',
            field=models.CharField(max_length=15),
        ),
    ]
