# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_auto_20161125_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignIn',
            new_name='SignUp',
        ),
    ]
